name: Scraper Automático

on:
  schedule:
    - cron: "0 8 * * *"   # roda todos os dias às 8h UTC
  workflow_dispatch:      # permite rodar manualmente

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install requests pandas

      - name: Executar scraper
        run: python aerofolio.py

      - name: Commitar resultado
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add produtos_aerofolio.csv
          git commit -m "Atualização automática dos dados"
          git push
